import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import {
  Grid,
  Card,
  CardContent,
  Avatar,
  Typography,
  Button,
  Rating,
  Stack,
  Box,
  styled,
  Paper,
  CardActions,
  CardMedia,
  Dialog,
  DialogContent,
  DialogContentText,
  DialogTitle,
} from "@mui/material";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === "dark" ? "#1A2027" : "#fff",
  ...theme.typography.body2,
  padding: theme.spacing(6),
  textAlign: "center",
  color: theme.palette.text.secondary,
  boxShadow: "none",
}));

export default function Home() {
  const [value, setValue] = React.useState<number | null>(5);
  return (
    <>
      <Head>
        <title>Velociventas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* carousel b */}

      {/* formulario 1 g */}
      <Grid container spacing={2} justifyContent="center">
        <Grid item xs={12} sm={12}>
          <Paper
            style={{
              height: "auto",
              background: "lightgrey",
              paddingBottom: 70,
              boxShadow: "none",
            }}
          >
            <Grid
              container
              spacing={0}
              direction="column"
              alignItems="center"
              justifyContent="center"
              paddingTop={5}
              // paddingBottom={5}
            >
              <Grid item xs={3}>
                <Typography
                  display="block"
                  variant="caption"
                  align="center"
                  sx={{ fontSize: 32 }}
                >
                  Si ellos lo recomiendan, anímate tu también.
                </Typography>
              </Grid>
              <Grid item xs={3}>
                <Typography
                  display="block"
                  variant="caption"
                  align="center"
                  sx={{ fontSize: 18 }}
                >
                  Por que nuestra mejor carta de presentación es la
                  recomendación.
                </Typography>
              </Grid>
            </Grid>
            <Grid
              container
              direction="row"
              justifyContent="center"
              alignItems="center"
              columnGap={4}
              rowGap={4}
              m={0}
              paddingTop={2}
            >
              <Card sx={{ maxWidth: 450, maxHeight: 400 }}>
                <Grid
                  container
                  spacing={0}
                  direction="column"
                  alignItems="center"
                  justifyContent="center"
                  style={{ height: "420px" }}
                >
                  <Grid item xs={3}>
                    <Grid item xs={3}>
                      <Card
                        sx={{
                          height: 420,
                          width: 345,
                          boxShadow: "none",
                          border: "0px solid #ced4da",
                          bgcolor: "#EE811C",
                        }}
                      >
                        <CardContent sx={{ marginLeft: 0 }}>
                          <Grid container wrap="nowrap" spacing={2}>
                            <Grid
                              item
                              container
                              spacing={0}
                              alignItems="center"
                              justifyContent="center"
                              flexDirection={"column"}
                              paddingTop={1}
                            >
                              <Avatar
                                alt="Remy Sharp"
                                src="https://content.app-sources.com/s/03275370429034195/thumbnails/640x480/Images/testimonio1-0952640.png"
                                sx={{ width: 70, height: 70 }}
                              />
                              <br />
                              <Typography sx={{ marginTop: 1, color: "white" }}>
                                Jimena Del Monte
                              </Typography>
                              <br />
                              <Rating name="read-only" value={value} readOnly />
                            </Grid>
                          </Grid>
                          <Grid
                            container
                            spacing={1}
                            alignItems="center"
                            justifyContent="center"
                            paddingTop={1}
                            color="white"
                            fontSize={19}
                          >
                            <br />
                            <Typography
                              display="block"
                              color="white"
                              maxWidth={250}
                              paddingTop={2}
                              variant="caption"
                              align="center"
                              fontSize={16}
                            >
                              "Estoy muy agradecido por la forma en que me
                              atendieron, los recursos que me brindaron para
                              explotar mi proyecto y obtener ganancias."
                            </Typography>
                          </Grid>
                        </CardContent>
                      </Card>
                    </Grid>
                  </Grid>
                </Grid>
              </Card>
              <Card sx={{ maxWidth: 450, maxHeight: 400 }}>
                <Grid
                  container
                  spacing={0}
                  direction="column"
                  alignItems="center"
                  justifyContent="center"
                  style={{ height: "420px" }}
                >
                  <Grid item xs={3}>
                    <Grid item xs={3}>
                      <Card
                        sx={{
                          height: 420,
                          width: 345,
                          boxShadow: "none",
                          border: "0px solid #ced4da",
                          bgcolor: "#FFFF",
                        }}
                      >
                        <CardContent sx={{ marginLeft: 0 }}>
                          <Grid container wrap="nowrap" spacing={2}>
                            <Grid
                              item
                              container
                              spacing={0}
                              alignItems="center"
                              justifyContent="center"
                              flexDirection={"column"}
                              paddingTop={1}
                            >
                              <Avatar
                                alt="Remy Sharp"
                                src="https://content.app-sources.com/s/03275370429034195/uploads/Images/testimonio3-0953090.png"
                                sx={{ width: 70, height: 70 }}
                              />
                              <br />
                              <Typography sx={{ marginTop: 1, color: "black" }}>
                                Francisco García
                              </Typography>
                              <br />
                              <Rating name="read-only" value={value} readOnly />
                            </Grid>
                          </Grid>
                          <Grid
                            container
                            spacing={1}
                            alignItems="center"
                            justifyContent="center"
                            paddingTop={1}
                            color="white"
                            fontSize={19}
                          >
                            <br />
                            <Typography
                              display="block"
                              color="black"
                              maxWidth={250}
                              paddingTop={2}
                              variant="caption"
                              align="center"
                              fontSize={16}
                            >
                              "Estoy muy agradecido por la forma en que me
                              atendieron, los recursos que me brindaron para
                              explotar mi proyecto y obtener ganancias."
                            </Typography>
                          </Grid>
                        </CardContent>
                      </Card>
                    </Grid>
                  </Grid>
                </Grid>
              </Card>
              <Card sx={{ maxWidth: 450, maxHeight: 400 }}>
                <Grid
                  container
                  spacing={0}
                  direction="column"
                  alignItems="center"
                  justifyContent="center"
                  style={{ height: "420px" }}
                >
                  <Grid item xs={3}>
                    <Grid item xs={3}>
                      <Card
                        sx={{
                          height: 420,
                          width: 345,
                          boxShadow: "none",
                          border: "0px solid #ced4da",
                          bgcolor: "#FFFF",
                        }}
                      >
                        <CardContent sx={{ marginLeft: 0 }}>
                          <Grid container wrap="nowrap" spacing={2}>
                            <Grid
                              item
                              container
                              spacing={0}
                              alignItems="center"
                              justifyContent="center"
                              flexDirection={"column"}
                              paddingTop={1}
                            >
                              <Avatar
                                alt="Remy Sharp"
                                src="https://content.app-sources.com/s/03275370429034195/thumbnails/640x480/Images/testimonio2-0953081.png"
                                sx={{ width: 70, height: 70 }}
                              />
                              <br />
                              <Typography sx={{ marginTop: 1, color: "black" }}>
                                María Velásquez
                              </Typography>
                              <br />
                              <Rating name="read-only" value={value} readOnly />
                            </Grid>
                          </Grid>
                          <Grid
                            container
                            spacing={1}
                            alignItems="center"
                            justifyContent="center"
                            paddingTop={1}
                            color="white"
                            fontSize={19}
                          >
                            <br />
                            <Typography
                              display="block"
                              color="black"
                              maxWidth={250}
                              paddingTop={2}
                              variant="caption"
                              align="center"
                              fontSize={16}
                            >
                              ¡Generarán el plan de acción para que tus ventas
                              crezcan y tengas muy claro como lograr lo que te
                              has propuesto!
                            </Typography>
                          </Grid>
                        </CardContent>
                      </Card>
                    </Grid>
                  </Grid>
                </Grid>
              </Card>
            </Grid>
          </Paper>
        </Grid>
      </Grid>

      {/* acerca de b */}

      {/* tarjetas de opinion g */}

      {/* formulario 2 b */}

      {/* contacto y footer g */}
    </>
  );
}
